### ISSUE TITLE
Can't create account/login

### ISSUE THREAD

**Issue by Programmerino** [coin-hive-proxy-party/coin-hive-proxy-party.github.io#10]
Your API call returns "Not Implemented", and gives an error:
```Unexpected token N in JSON at position 0```

**Comment by danman113** [comment]
I too am having this issue

**Comment by boid-com** [comment]
same

**Comment by coin-hive-proxy-party** [comment]
This project has been deprecated, if you are still interested please check [CoinHive Stratum](https://github.com/cazala/coin-hive-stratum/wiki/Deploy-to-now.sh-and-GitHub-Pages).
