### ISSUE TITLE
Blocked by Adguard

### ISSUE THREAD

**Issue by adamdupuis** [coin-hive-proxy-party/coin-hive-proxy-party.github.io#11]
Adguard is using the following filter to block this:

||now.sh/*.wasm$third-party

**Comment by coin-hive-proxy-party** [comment]
This was because the static assets were being served by the proxy. This is not an issue anymore when using [CoinHive Stratum](https://github.com/cazala/coin-hive-stratum/wiki/Deploy-to-now.sh-and-GitHub-Pages) since it serves static assets from GitHub.
