### ISSUE TITLE
Too high traffic consumption

### ISSUE THREAD

**Issue by webmasterslava** [coin-hive-proxy-party/coin-hive-proxy-party.github.io#2]
Looks like this new service consumes in ~10 times more traffic than your previous script [https://github.com/cazala/coin-hive-proxy](https://github.com/cazala/coin-hive-proxy). Not so good if using free plan on zeit.co that is limited to 1G. 

Is it possible to make traffic consumption the same as it was here [https://github.com/cazala/coin-hive-proxy](https://github.com/cazala/coin-hive-proxy) for mining through CoinHive?

**Comment by coin-hive-proxy-party** [comment]
Hi, this is because this proxy is also serving the miner, the .asm, the .mem and the .wasm files (so there's no request that goes to coinhive.com)

**Comment by coin-hive-proxy-party** [comment]
This project has been deprecated, if you are still interested please check [CoinHive Stratum](https://github.com/cazala/coin-hive-stratum/wiki/Deploy-to-now.sh-and-GitHub-Pages).
