### ISSUE TITLE
[Question] Proxy Hardcoded Donation?

### ISSUE THREAD

**Issue by Ratnet** [coin-hive-proxy-party/coin-hive-proxy-party.github.io#4]
Hello there,

First of all great work by doing this. I have one question. Does this proxy have some kind of hardcoded donation on the code for this address 46WNbmwXpYxiBpkbHjAgjC65cyzAxtaaBQjcGpAZquhBKw2r8NtPQniEgMJcwFMCZzSBrEJtmPsTR54MoGBDbjTi2W1XmgM and for this API-KEY for CoinHive PuwigKuHSIbrfs0JTw1QzHScz7L2IKgn? Specifically for this pools? 

> [{
                name: "coinhive",
                label: "CoinHive",
                proxies: ["wss://ws001.coinhive.com/proxy", "wss://ws002.coinhive.com/proxy", "wss://ws003.coinhive.com/proxy", "wss://ws004.coinhive.com/proxy", "wss://ws005.coinhive.com/proxy", "wss://ws006.coinhive.com/proxy", "wss://ws007.coinhive.com/proxy", "wss://ws029.coinhive.com/proxy", "wss://ws008.coinhive.com/proxy", "wss://ws009.coinhive.com/proxy", "wss://ws010.coinhive.com/proxy", "wss://ws011.coinhive.com/proxy", "wss://ws012.coinhive.com/proxy", "wss://ws013.coinhive.com/proxy", "wss://ws014.coinhive.com/proxy", "wss://ws030.coinhive.com/proxy", "wss://ws015.coinhive.com/proxy", "wss://ws016.coinhive.com/proxy", "wss://ws017.coinhive.com/proxy", "wss://ws018.coinhive.com/proxy", "wss://ws019.coinhive.com/proxy", "wss://ws020.coinhive.com/proxy", "wss://ws021.coinhive.com/proxy", "wss://ws031.coinhive.com/proxy", "wss://ws022.coinhive.com/proxy", "wss://ws023.coinhive.com/proxy", "wss://ws024.coinhive.com/proxy", "wss://ws025.coinhive.com/proxy", "wss://ws026.coinhive.com/proxy", "wss://ws027.coinhive.com/proxy", "wss://ws028.coinhive.com/proxy", "wss://ws032.coinhive.com/proxy"],
                diff: 256,
                commision: "30%"
            }, {
                name: "supportxmr",
                label: "supportXMR.com",
                host: "la01.supportxmr.com",
                port: 3333,
                diff: 1e3,
                commision: "0.6%"
            }, {
                name: "usxmrpool",
                label: "US XMR Pool",
                host: "pool.usxmrpool.com",
                port: 2222,
                diff: 3e3,
                commision: "0.5%"
            }, {
                name: "minexmr",
                label: "mineXMR.com",
                host: "pool.minexmr.com",
                port: 4444,
                diff: 15e3,
                commision: "1%"
            }, {
                name: "nanopool",
                label: "Nanopool",
                host: "xmr-eu1.nanopool.org",
                port: 14444,
                diff: 15e4,
                commision: "1%"
            }]

> 
If not can you please explain those lines to me?

Thank you and Cheers!

**Comment by coin-hive-proxy-party** [comment]
Yes, that's the donation address.

This project has been deprecated, if you are still interested please check [CoinHive Stratum](https://github.com/cazala/coin-hive-stratum/wiki/Deploy-to-now.sh-and-GitHub-Pages).
