### ISSUE TITLE
What's the need for now.sh proxies?

### ISSUE THREAD

**Issue by monerominerz** [coin-hive-proxy-party/coin-hive-proxy-party.github.io#5]
Would you mind explaining why now.sh or any proxy is needed?

Would it not be possible to create a javascript file with your Monero address hard coded into it that connects to the pool of your choice without the need for proxies to be between a user and the pool's server?

And if so, why would Coin-Hive's code need to be used at all?

There seems to be a lot of code on GitHub focused around mining Moneros based on Coin-Hive's code, but nothing that's really "standalone".  Wasn't sure if I was missing something...

**Comment by coin-hive-proxy-party** [comment]
You can't connect from a browser to a pool directly. Pools accept TCP connections, while browsers use WebSockets. Also the protocol used by CoinHive's miner is a custom one, and not the one used by the rest of the pools. The proxy takes WebSocket connections pipes them through a TCP socket to the pool, and also translate CoinHive messages intro Stratum messages, and vice-versa.

This project has been deprecated, if you are still interested please check [CoinHive Stratum](https://github.com/cazala/coin-hive-stratum/wiki/Deploy-to-now.sh-and-GitHub-Pages).
