### ISSUE TITLE
Is it possible to use a fork of coin-hive-stratum?

### ISSUE THREAD

**Issue by tangrufus** [coin-hive-proxy-party/coin-hive-proxy-party.github.io#6]
> It uses [coin-hive-stratum](https://github.com/cazala/coin-hive-stratum) under the hood 
> -- Project Readme

Is it possible to use a fork of coin-hive-stratum?

**Comment by coin-hive-proxy-party** [comment]
This project has been deprecated, if you are still interested please check [CoinHive Stratum](https://github.com/cazala/coin-hive-stratum/wiki/Deploy-to-now.sh-and-GitHub-Pages).
