### ISSUE TITLE
Getting error when creating new proxy "Error Missing or invalid `name` field"

### ISSUE THREAD

**Issue by lettersnumbers** [coin-hive-proxy-party/coin-hive-proxy-party.github.io#8]
![image](https://user-images.githubusercontent.com/33428822/33135083-6d03eed2-cf6f-11e7-83c9-45ca1427e941.png)

I have since created a zeit account, which is now active, but it's looking for some kind of 'name' input. 

I clearly filled out the host, port & diff in the form. Any ideas?

**Comment by lettersnumbers** [comment]
Now this is the error, trying again after a couple days:

![image](https://user-images.githubusercontent.com/33428822/33225037-7c0aecb6-d13e-11e7-88d5-646afc239245.png)

**Comment by coin-hive-proxy-party** [comment]
This project has been deprecated, if you are still interested please check [CoinHive Stratum](https://github.com/cazala/coin-hive-stratum/wiki/Deploy-to-now.sh-and-GitHub-Pages).
