### ISSUE TITLE
[BUG] Deployments dying randomly on now.sh.

### ISSUE THREAD

**Issue by matthewlilley** [coin-hive-proxy-party/coin-hive-proxy-party.github.io#9]
![image](https://i.imgur.com/BOusp70.jpg)

**Comment by coin-hive-proxy-party** [comment]
This project has been deprecated, if you are still interested please check [CoinHive Stratum](https://github.com/cazala/coin-hive-stratum/wiki/Deploy-to-now.sh-and-GitHub-Pages).
